# Generated by Django 5.0.3 on 2024-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmsetting',
            name='alarm_time',
        ),
        migrations.RemoveField(
            model_name='alarmsetting',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='alarmsetting',
            name='message',
        ),
        migrations.AddField(
            model_name='alarmsetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alarmsetting',
            name='alarm_type',
            field=models.CharField(choices=[('motion', 'Motion Detector'), ('door_window', 'Door/Window Sensor'), ('smoke', 'Smoke Detector')], default='motion', max_length=50),
        ),
        migrations.AddField(
            model_name='alarmsetting',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
    ]
