# Generated by Django 5.0.3 on 2024-04-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_alarmsetting_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmsetting',
            name='activation_time',
        ),
        migrations.RemoveField(
            model_name='alarmsetting',
            name='deactivation_time',
        ),
    ]
